language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build -c pre-prod
  - cd dist/compagnon-de-visite
  - zip -r "${TRAVIS_BUILD_DIR}/compagnon-de-visite_${TRAVIS_TAG}.zip" * 
  
deploy:
  provider: releases
  api_key:
    secure: Fw5TIcSO8a7DL9TQGJTuhJQjYyDa+eJODawK/pq4RhiJHpoYNNXYOnXmtxPvatIIoKz92HiR3U0m1ilSbJmEuvtNCx6U6eV9IPQx3Zyi88nG7jGangEKPsZalx8vMiHLykCXEY2bnPZdYIme4AEbDBzaBm07oXT5EcnV5ZZ0u2CLnlE0yftglAS89SjuzJgEU5AGGOyGzNl+jsRNfBMH4E9E9+xHo4GMKHmhESZuJ4LsCnDWH2SYwElYDR3DnpbsPBPF2Gps4duQJNRHHJLMXRzIel6/cq0sQ2jqGPLGJ2W+esX7H8/ktLJ4fpbUL3A1EpxPvAcUgFo7AXeQZkCTyHIBoM6cfiAjh7o/Y5Z/rX4t7TokiwBLXLfT3CvTsRUTZzMLpd66+Y5czflrXqzcLDylzWyRI4rNrRCQjRtCz/aonZgo6TL6HKUnD64MZ+aQ3WMcyyIz+L5f+xHCITsHKmMD1jmdCqO14ZoTqqwMpy3G7koBeJZpxcep/N053n4wXI8DmgSZ6R7r25mA+K9wazIzEjs6JpHftDySXCUaSuZDtvBSkMOBFuivdztROELCdHjAG/xAUdE/09xasMqxiHWrBRDelGvVbfOfrEN19lS5Tw+vEYtWKuvjyZet4lFURiam/tV8Ir+1SJI88VVVnyu3cCOZAGI7SfEHMxOUQ8o=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/*.zip"
  skip_cleanup: true
  on:
    tags: true
