language: node_js

node_js:
  - 16

install:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build -c pre-prod
  - cd dist/compagnon-de-visite
  - zip -r "${TRAVIS_BUILD_DIR}/compagnon-de-visite_${TRAVIS_TAG}.zip" * 
  
deploy:
  provider: releases
  api_key:
    secure: fCq/sicEjgglsAVohatC2aLNWmyAbZIO62OUnuzRZn9P+gWNSOWpor294/kN0UMKZpoFo+dc66KMVrYFbb4vip3exnTUe4tU8UXuo0OwTQhnJ34Waf2V52GCiA/kJFRcj3TB/OZYyCD8qbSkIHZ2FfG65rbuQKhxfNwXZxTuNQVim3n1ah3EA5ZK7hNpOYg11ETLmtcOyAWhGjO52KuLBjuNGq6N5wKykAdueRfetLcd+jZKLJgEi5jFceeumYXKzoYxarDDeONgpzDUqrCXXnuA49rvlxDMdG1uj1hPswBNtndP9bnELzrraanFS1df8tAuocFa9Pkgt+XhF05FHBT2Dndy/zpJ5TX5h9wTD0RWUufme6+742QRPCSiPAeUIyIWNVpFExST53ejzYWGfnXok2bdJPpJrGTkm1Nz3hGFZVqWJZwQDsZeTqoUBbTciZUU1zd6plbaoDuXOAT4TkoL78A/F6j9SX8upi/eUFPR45umCDctmHh9ep1psK2cLHJghWyKNaz6OBbLeNEZOvX3Z7zhHH5pyrqDcgTmAeZ9lbSmmQFDEw7de3BQxid/evcKHmFGNDI4Dp2uHtm/iqAJkO2fouYFq0ZjJ7TXBhsCIGKMOJfNcdcYHqx7FzzSNxm9GM9YAkOiURTDr5DB2nsbMHiIKmpyfVV2ialiuus=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/*.zip"
  skip_cleanup: true
  on:
    tags: true
